@extends('layouts.app')
@section('title', 'Terms and Conditions | CarNext - User Agreement and Policies')

@section('meta_description', 'Review the terms and conditions for using CarNext. Understand our user agreement, policies, and legal guidelines. Ensure you are informed about your rights and responsibilities when using our services.')

@section('content')
<section class="info_page_main section_padding" id="subpage_mt">
    <div class="container">
        <div class="row">
            <div class="col col-12">
                <div class="info_page_heading section_heading text-center">
                    <h2>Terms and Conditions</h2>
                </div>
            </div>
            <div class="col col-12">
                <div class="info_page_content">
                <p><strong>Thank you for visiting our Platform, presented to you by CarNext, Inc.</strong> (referred to as “CarNext,” “we,” or “us”). These <a href="#">Terms of Use</a> (“Platform Terms”) govern your access to, and use of, www.carnext.autos CarNext mobile applications and any other website, application, or online service owned or operated by CarNext that posts a link to these Platform Terms (collectively, the “Platform”).</p>

                        <p>Please read these Platform Terms carefully, including the mandatory <a href="#">Binding Arbitration Agreement</a>, which requires that disputes be resolved by final and binding arbitration on an individual and not class-wide or consolidated basis. You affirm that you have the capacity and authority to agree to these Terms. These Platform Terms apply solely to your access to and use of the Platform and do not alter in any way the terms or conditions of any other agreement you may have with CarNext.</p>

                        <p>In some instances, both these Platform Terms and separate terms and conditions may apply to a service we offer (any “Additional Terms”). To the extent there is a conflict between these Platform Terms and any Additional Terms, the Additional Terms will control unless the Additional Terms expressly state otherwise.</p>

                        <p>By accessing, browsing, or using the Platform, you agree to be bound by the terms and conditions set forth in, any Additional Terms, and any policies referenced by, these Platform Terms, including any subsequent changes to the foregoing. If you do not agree to these Platform Terms, do not access, browse, or otherwise use the Platform.</p>

                        <p><strong>TABLE OF CONTENTS</strong></p>
                        <p>
                        1. <a href="#section1">WE ONLY PROVIDE THE PLATFORM</a><br>
                        2. <a href="#section2">PRIVACY</a><br>
                        3. <a href="#section3">ACCOUNT REGISTRATION, ACCESS TO THE PLATFORM, TERMINATION</a><br>
                        4. <a href="#section4">OWNERSHIP AND LIMITED LICENSE TO USE MATERIALS</a><br>
                        5. <a href="#section5">PROHIBITED USE OF THE PLATFORM AND MATERIALS</a><br>
                        6. <a href="#section6">USER-CONTENT SUBMISSIONS</a><br>
                        7. <a href="#section7">USER INTERACTIONS AND DISPUTES</a><br>
                        8. <a href="#section8">ACCEPTABLE USE POLICY</a><br>
                        9. <a href="#section9">COPYRIGHT & OTHER IP COMPLAINTS</a><br>
                        10. <a href="#section10">LINKS AND THIRD-PARTY CONTENT</a><br>
                        11. <a href="#section11">SOCIAL DISTRIBUTION AND WIDGETS</a><br>
                        12. <a href="#section12">MOBILE FEATURES</a><br>
                        13. <a href="#section13">LINKING POLICY</a><br>
                        14. <a href="#section14">CONTESTS, SWEEPSTAKES, AND OTHER INTERACTIVE TRANSACTIONS</a><br>
                        15. <a href="#section15">DISCLAIMER OF WARRANTIES; WAIVER</a><br>
                        16. <a href="#section16">LIMITATION OF LIABILITY</a><br>
                        17. <a href="#section17">INDEMNITY</a><br>
                        18. <a href="#section18">APPLICABLE LAW AND VENUE</a><br>
                        19. <a href="#section19">BINDING ARBITRATION AGREEMENT</a><br>
                        20. <a href="#section20">LOCATION OF THE PLATFORM AND TERRITORIAL RESTRICTIONS</a><br>
                        21. <a href="#section21">GENERAL-AUDIENCE SITE</a><br>
                        22. <a href="#section22">SPECIAL TERMS FOR APPLE IOS USERS</a><br>
                        23. <a href="#section23">CHANGES TO THESE TERMS</a><br>
                        24. <a href="#section24">GENERAL TERMS</a><br>
                        25. <a href="#section25">CONTACT INFORMATION</a><br>
                        </p>

                        <p id="section1"><strong>1. WE ONLY PROVIDE THE PLATFORM</strong></p>
                        <p>CarNext provides an online marketplace that matches consumers and dealerships to transact directly for sales of vehicle inventory. As described herein, the Platform contains content that is proprietary to us or that is licensed or authorized for use by us as well as content provided by you including vehicle specifications, texts, photos, videos, chats, and other materials.</p>
                        <p>As the provider of the Platform, we do not provide, control, manage, offer, deliver, or supply any vehicle inventory, listings, or bids. You and the dealerships are responsible for the listing and any subsequent dealings related to the listing including bids, instant offers, and consummating any transactions thereof. When you engage in a transaction, you and the dealership are entering into a contract directly with each other. We are not, and do not become, a party to or other participant in any contractual relationship between you and any dealership.</p>
                        <p>We have no control over and do not guarantee (1) the existence, quality, safety, suitability, or legality of any vehicle listed, (2) the truth or accuracy of any User Content (as defined below), or (3) the performance or conduct of any dealerships. We do not endorse any dealership or listing. You should always exercise due diligence and care when deciding whether to communicate, interact with, and engage in any transaction with any dealership, whether online or in person.</p>

                        <p id="section2"><strong>2. PRIVACY</strong></p>
                        <p>Please refer to CarNext’s <a href="{{ route('privacy')}}">Privacy Policy</a> to understand how CarNext collects, uses, and discloses personal information through the Platform.</p>

                        <p id="section3"><strong>3. ACCOUNT REGISTRATION, ACCESS TO THE PLATFORM, TERMINATION</strong></p>
                        <p>a. Certain areas and features of the Platform may require registration with CarNext or a third party or may otherwise ask or require you to provide information to participate. When you choose to provide information to the Platform, you agree to provide only true, accurate, current, and complete information. If you submit personal information to CarNext to register for an account with CarNext or to otherwise participate in any services offered by CarNext on the Platform, that information will be governed by our <a href="{{ route('privacy') }}">Privacy Policy</a>. If you register with us, you agree that you will not sell or otherwise transfer your account or account rights. You are responsible for maintaining the confidentiality and security of your account credentials. You must immediately notify us if you know or have any reason to suspect that your credentials have been lost, stolen, or otherwise compromised or in case of any actual or suspected unauthorized use of your account. You are liable for any and all activities conducted through your account.</p>
                        <p>If you “sign in” with a third-party login such as Facebook, LinkedIn, Twitter, etc. or otherwise allow us to access or use any profile or other information about you that you have provided to a third-party website, you acknowledge and agree that the information or content that is a part of your social media site profile, which you have designated as “public” (or a similar designation), may be accessed, and used by us in connection with the Platform.</p>

                        <p>b. You acknowledge that CarNext reserves the sole right, in its sole discretion, to update, modify, replace, or alter any aspect of the Platform, in whole or in part, from time to time without any liability to you. You acknowledge that CarNext may, in its sole discretion, cease to operate the Platform or features within the Platform. CarNext reserves the right to deny you access in its sole discretion without notice at any time and without any liability to you.</p>

                        <p>c. CarNext reserves the right to modify, suspend, terminate, or restrict your use of any portion of the Platform or otherwise deny you access, in its sole discretion, at any time, and to the extent permitted by applicable law, without notice. We shall not be liable to you or to any third party for any cancellation, termination, suspension or discontinuance of the Platform or your account. We also reserve the right to investigate suspected violations of these Platform Terms or any Additional Terms. Any violation of these Platform Terms or Additional Terms may be referred to law-enforcement authorities.</p>

                        <p>d. You agree that you will be responsible for obtaining and maintaining all telephone (including mobile), computer hardware and other equipment needed to access and use the Platform. You also agree to comply with all rules, laws and regulations that are applicable to your use of the Platform, including, without limitation, those governing your transmission or use of any software or data.</p>

                        <p id="section4"><strong>4. OWNERSHIP AND LIMITED LICENSE TO USE MATERIALS</strong></p>
                        <p>a. The trademarks, service marks and logos (“Trademarks”) used and displayed on the Platform, all materials included in or otherwise part of the Platform (including but not limited to past, present, and future versions, images and text, domain name, source and object code, design, manuals, product information, graphics, images, pictures, sound and other files, and the selection and arrangement thereof and the elements that make up its “look and feel”) (collectively, “Materials”) are owned, controlled, or licensed by CarNext and its subsidiaries or affiliates and others and are protected from unauthorized use, copying, dissemination by intellectual property laws including copyright, trademark, patents, and other laws, rules, regulations, and treaties. The Materials may not be copied, reproduced, downloaded, or distributed in any way, in whole or in part, except with the express permission of CarNext. CarNext claims neither ownership in, nor any affiliation with, any third-party trademarks appearing on the Platform. Such third-party trademarks are used only to identify their owners.</p>

                        <p>b. You may visit the Platform without further permission and CarNext grants you a limited, personal, non-exclusive, revocable, and non-transferable license to make personal use only of the Materials for information purposes only, including to (i) download Materials that are made available for download, (ii) use a link on the Platform to share a link or Materials as permitted by the sharing mechanism, and (iii) linking to the Platform using a plain-text link from a site that you own or control.</p>

                        <p>c. This license is subject to these Platform Terms, and does not include the right to: (i) use the Platform or Materials other than for its intended purpose; (ii) use framing techniques to enclose any portion of the Platform, including any images found on the Platform or any text or the layout or design of any page or form contained on a page; (iii) publish, publicly perform or display, or distribute to any third party any Materials, including reproduction or hosting the Materials on any computer network or broadcast or publications media; (iv) resell, copy, distribute, transfer, reverse engineer, disassemble, create derivative works thereof, or allow third-party access to the Platform or the Materials; (v) any systematic collection or extraction of data through the use of any data mining, robots or similar data gathering or extraction methods; (vi) use the Platform or Materials surrounded by or on the same page as other content that presents false information about, disparages, tarnishes, or otherwise harms us or our products or services or may be construed as offensive, controversial, or otherwise objectionable; or (vii) imply that we or the Platform are endorsing, sponsoring, or otherwise affiliated with any third party or its products or services.</p>

                        <p>d. You are not conveyed any other right or license, by implication, estoppel or otherwise, in or under any patent, trademark, or proprietary right of CarNext or any third party. Any unauthorized use of the Platform will terminate the permission or license granted by these Platform Terms and may violate applicable law, including but not limited to copyright laws, trademark laws (including trade dress), and communications regulations and statutes.</p>

                        <p id="section5"><strong>5. PROHIBITED USE OF THE PLATFORM AND MATERIALS</strong></p>
                        <p>In addition to other prohibitions as set forth in these Platform Terms, you may not use the Platform or Materials:</p>
                        <p>a. For any unlawful purpose or to solicit others to perform or participate in any unlawful acts;</p>
                        <p>b. To engage in any activity that might be harmful to minors or others;</p>
                        <p>c. To change or remove any author attribution, trademark, legend, or copyright notice or otherwise to infringe upon or violate our intellectual property rights or the intellectual property rights of others;</p>
                        <p>d. To harass, abuse, insult, harm, defame, slander, disparage, threaten, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability;</p>
                        <p>e. To submit false or misleading information;</p>
                        <p>f. To transmit “junk mail” or unsolicited mass mailing or “spam;”</p>
                        <p>g. Except as part of standard use of a search engine or browser, download, monitor, mine, copy, or otherwise reproduce, store, or distribute the Platform or any Materials.</p>
                        <p>h. Violate any international, federal, provincial, or state regulations, rules, laws, or local ordinances.</p>
                        <p>i. To upload or transmit viruses of any other type of malicious code that will or may be used in any way that will affect the functionality, security or operation of the Platform or any related websites or the Internet;</p>
                        <p>j. To collect or track the personal information of others.</p>
                        <p>You agree that you will not: (a) use any robot, spider, other automatic device, or manual process to monitor or copy web pages of the Platform or for any other unauthorized purpose without our prior expressed written permission; (b) use any device, software, or routine to interfere or attempt to interfere with the proper working of the Platform; and (c) take any action that imposes an unreasonable or disproportionately large load on CarNext’s hardware and software infrastructure.</p>
                        <p>We reserve the right to terminate your use of the Platform for violating any of the prohibited uses or any other provisions of the Platform Terms.</p>

                        <p id="section6"><strong>6. USER-CONTENT SUBMISSIONS</strong></p>
                        <p>a. The Platform may provide you the ability to submit content to us or post content publicly on the Platform (including, without limitation, photographs, videos, vehicle specifications, bids on vehicles, writings, chats, data, questions, answers, comments etc.) (collectively,” User Content”).</p>
                        <p>b. Except as otherwise described in the posted <a href="{{ route('privacy') }}">Privacy Policy</a> or other agreement on the Platform where you provide your User Content, you agree that your User Content will be treated as non-confidential and non-proprietary and will not be returned.</p>
                        <p>c. You agree that you either: (i) own the rights to the User Content you submit and the right to grant all of the rights and licenses in these Platform Terms; or (ii) you have all necessary rights and licenses from the owner(s) of these rights to enter into these Platform Terms and grant CarNext the license below. Upon CarNext’s request, you will furnish CarNext any documentation, substantiation or releases necessary to verify your compliance with these Platform Terms.</p>
                        <p>d. CarNext is not responsible for the substance of any User Content and such User Content does not necessarily reflect the views of CarNext. We may, but are under no obligation to, monitor, edit or remove User Content that we determine in our sole discretion is unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene, or otherwise objectionable or violates any party’s intellectual property or these Platform Terms. We may remove or refuse to post any User Content for any reason in our sole discretion.</p>
                        <p>e. You also acknowledge that the Internet may be subject to breaches of security and should be aware that submissions of User Content or other information may not be secure, and you should consider this before submitting any information to CarNext.</p>
                        <p>f. You remain the owner of your User Content, but you acknowledge that CarNext must have a license from you in order to accept your User Content. Accordingly, you grant to CarNext an unrestricted, worldwide, irrevocable, perpetual, transferable, sublicensable, and royalty-free license (but not obligation) to host, use, copy, distribute, display, perform, modify, translate, store, or otherwise exploit all or any portion of your User Content for any purpose whatsoever in all formats, on or through any media, technology or device now known or hereafter developed. You agree that we may, at any time, without restriction, edit, copy, publish, reproduce, translate, distribute, share, and otherwise use in any medium any User Content without your further permission. We are and shall be under no obligation (1) to pay compensation for any User Content; or (2) to respond to any User Content.</p>
                        <p>g. You agree that CarNext is free to use any ideas or concepts contained in any User Content for any purposes whatsoever, including, without limitation, developing, manufacturing, and marketing products and services, and creating informational articles, without any payment of any kind to you. You authorize CarNext to publish your User Content in a searchable format that may be accessed by users of the Platforms and the Internet. This may include User Content that you submit through our accounts on social media websites (e.g., Facebook, Instagram, Twitter, LinkedIn, etc.). To the fullest extent permitted, you waive any moral rights you may have in any User Content you submit, even if such User Content is altered or changed in a manner not agreeable to you.</p>
                        <p>h. You acknowledge that CarNext may be working on or developing material similar or the same in nature to your User Content and that CarNext may have received similar or the same intellectual property rights from another party. CarNext owes you no obligation connected to your submissions unless you and CarNext enter a written agreement to that effect. Any discussion or negotiations between you and CarNext regarding your submissions does not constitute recognition of the novelty or originality of your User Content.</p>
                        <p>i. You agree that CarNext has no obligation to monitor or enforce your intellectual property rights to your User Content but has the right to protect and enforce its and its licensees’ rights to your User Content. CarNext will not have any obligation to you with regard to User Content and CarNext may or may not monitor, display, or accept your User Content and may delete it at any time. You are solely responsible for any User Content you submit and its accuracy. We take no responsibility and assume no liability for any User Content posted by you or any third-party.</p>

                        <p id="section7"><strong>7. USER INTERACTIONS AND DISPUTES</strong></p>
                        <p>You are solely responsible for your interaction with other users of the Platform, whether online or offline. We are not responsible or liable for the conduct of any user. We reserve the right, but have no obligation, to monitor or become involved in disputes between you and other users. Exercise common sense and your best judgment in your interactions with others, when you submit or post any personal or other information, and in all other online activities including if communicating using CarNext’s chat feature.</p>

                        <p id="section8"><strong>8. ACCEPTABLE USE POLICY</strong></p>
                        <p>When you contribute, upload, or otherwise provide User Content to the Platform, you agree to comply with the following rules:</p>
                        <p><strong>User Content must be yours.</strong> All User Content must be original with you, not copied from someone else’s work, and you must have all rights in the User Content; OR all persons who contributed in any way or have any rights to your User Content or otherwise appear in the User Content have given you permission to upload and distribute the User Content on the Platform and elsewhere.</p>
                        <p><strong>Do not include anyone in your User Content without permission.</strong> If you choose to upload photos to the Platform, links to embedded videos, or include images in which a person is seen, depicted, heard, named, identified, or otherwise included in your User Content, you must have express written permission to submit it and will provide us with evidence of such permission upon request.</p>
                        <p><strong>Do not upload third-party materials.</strong> Your User Content should not contain any visible logos, phrases or trademarks or other third-party materials without permission from the owner of the materials. Do not use any User Content that belongs to other people and pass it off as your own. This includes any content that you might have found elsewhere on the Internet.</p>
                        <p><strong>Keep it relevant.</strong> Your User Content should relate to the content on the Platform.</p>
                        <p><strong>Please follow codes of social decency.</strong> Express yourself with non-offensive individual self-expression. Be respectful of others’ opinions and comments. If you think your User Content might offend someone, chances are it probably will, and it does not belong on the Platform. Cursing, flaming, harassing, stalking, posting insulting comments, personal attacks, gossip, or similar actions are prohibited. Your User Content may not threaten, abuse, or harm others. Your User Content may not include any negative comments that are connected to race, national origin, gender, sexual orientation, religion, or physical handicap or that are defamatory, slanderous, indecent, obscene, pornographic, or sexually explicit.</p>
                        <p><strong>Do not post User Content to the Platform for commercial purposes that are not expressly permitted by these Platform Terms.</strong> Your User Content may not advertise or promote a product or service except those permitted on the Platform (i.e., vehicle listings). You may not use your User Content to raise money for anyone or for a pyramid or other multi-tiered marketing scheme. You may not engage in any activities that solicit passwords or personal information from other users for commercial or unlawful purposes.</p>
                        <p><strong>Do not upload User Content that is inappropriate or illegal.</strong> Your User Content may not promote any illegal activity. If someone could go to jail for taking action suggested by your User Content, do not upload, or post it. If you do upload or post User Content that is illegal or in violation of applicable law, we reserve the right to take action that we deem appropriate, in our sole discretion, including reporting you to the proper governmental authorities.</p>
                        <p><strong>No violence.</strong> Your User Content may not promote violence or describe how to perform a violent act.</p>
                        <p><strong>Be honest and do not misrepresent yourself or your User Content.</strong> Do not impersonate any other person, user or company or upload or post User Content that you know is false, fraudulent, deceptive, inaccurate, misleading or that misrepresents your identity or affiliation with a person or company. You may not use a false e‑mail address or otherwise mislead us or third parties as to the origin of any User Content.</p>
                        <p><strong>Public forum.</strong> Please remember that when you are submitting User Content to a public forum, User Content that you post will be accessible and viewable by other users. Do not post personal information (e.g., full name, password, phone number, address, e-mail address or other personally identifiable information or contact information).</p>
                        <p><strong>Do not share other people’s personal information.</strong> Your User Content may not reveal another person’s address, phone number, e-mail address, credit card number or any information that may be used to track, contact, or impersonate that individual or that is extremely personal in nature.</p>
                        <p><strong>Do not damage the Platform or anyone’s computers.</strong> User Content may not contain viruses, Trojan horses, spyware, or any other technologies that could impact the operation of the Platform or any computer system.</p>
                        <p>In cases where you feel threatened or believe someone else is in danger, you should contact your local law enforcement agency immediately.</p>

                        <p id="section9"><strong>9. COPYRIGHT & OTHER IP COMPLAINTS</strong></p>
                        <p>a. You may not use the Platform for any purpose or in any manner that infringes the rights of any third party. CarNext encourages you to report any content on Platform that you believe infringes your rights. Only the intellectual property rights owner or person authorized to act on behalf of the owner can report potentially infringing content. If you have a good faith belief that content on Platform infringes your copyright, trademark, or other intellectual property rights, please follow the procedures set forth below.</p>
                        <p>b. In accordance with the Digital Millennium Copyright Act of 1998 (the “DMCA”), CarNext has a designated agent for receiving notices of copyright infringement and CarNext follows the notice and takes down procedures of the DMCA. If you believe your work or content has been copied and posted to the Platform in a way that constitutes copyright infringement, please provide our copyright agent the following written information in accordance with the Digital Millennium Copyright Act (DMCA):</p>
                        <p>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;</p>
                        <p>A description of the copyrighted work that you claim has been infringed upon;</p>
                        <p>A description of where the material that you claim is infringing is located on the Platform;</p>
                        <p>Your name, address, phone number and email address (if any);</p>
                        <p>A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</p>
                        <p>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.</p>
                        <p>CarNext’s DMCA Copyright Agent for notice of claims of copyright infringement can be reached at:</p>
                        <p>CarNext, Inc.<br>
                        Attn: Legal Dept CarNext<br>
                        722 Dulaney Valley Rd, Suite #322<br>
                        Townson, MD 21284<br>
                        866-715-9409<br>
                        <a href="mailto:support@carnext.autos">support@carnext.autos</a></p>
                        <p>We suggest that you consult your legal advisor before filing a notice with CarNext’s copyright agent, because there may be penalties for false claims.</p>
                        <p>NOTE: This contact information is for inquiries regarding potential copyright and other intellectual-property infringement only.</p>
                        <p>c. If you believe that any content on the Platform violates your exclusive rights other than copyrights, please provide us at least the following information: (a) your physical or electronic signature; (b) identification of the material that you claim is infringing your exclusive rights and information reasonably sufficient to permit us to locate the material; (c) an explanation of the exclusive rights that you own/have and why the you believe the content infringes those rights, sufficient for us to evaluate the complaint; and (d) accurate contact information for you. Please send your complaint regarding content on the Platform to our designated agent using the contact information above.</p>
                        <p>d. We have a policy of terminating the accounts of users who (in our reasonable discretion) are repeat infringers. It is often difficult to determine if your intellectual property rights have been violated or if the DMCA requirements have been met. We may request additional information before we remove any infringing material. If a dispute develops as to the correct owner of the rights in question, we reserve the right to remove your content along with that of the alleged infringer pending resolution of the matter. A copy of your notice, including any contact information provided, may be provided to third parties, including the complainant or the user who posted the content being reported.</p>

                        <p id="section10"><strong>10. LINKS AND THIRD-PARTY CONTENT</strong></p>
                        <p>CarNext or third parties may provide links or functionality on the Platform or in communications from us to other third-party sites or content. CarNext has no control over such sites or content, and therefore makes no claim or representation regarding, and expressly disclaims responsibility for, the quality, content, nature or reliability of sites or content linked to by the Platform. CarNext provides links to you only as a convenience, and the inclusion of any link on the Platform does not imply our affiliation, endorsement, or adoption of the linked site or any information therein. If you choose to connect your information on the Platform with a third-party site or feature, you consent to sharing that information and understand that your information may be publicly disclosed. Our terms and policies govern any time you visit the Platform directly or indirectly through authorized third-party sites. You should review applicable terms and policies, including the privacy and data gathering practices, of any third-party sites.</p>
                        <p>Neither CarNext nor its service providers are responsible for the practices of any third parties. Your correspondence and business dealings with third parties found through the Platform, including without limitation, payment and delivery of vehicles, any terms, conditions, warranties, representations associated with such dealings are between you and the third party. You acknowledge and agree that CarNext is not liable for any loss or damage which may be incurred by you as a result of your interaction with any third party.</p>

                        <p id="section11"><strong>11. SOCIAL DISTRIBUTION AND WIDGETS</strong></p>
                        <p>CarNext may allow you to engage in certain personal uses of Materials that include the ability to share Materials with others ("Social Distribution"). For example, the Platform may allow you to send Materials to friends, display Materials on your personal website or post Materials on a third-party website. You understand that only CarNext can make claims, promises or statements on behalf of CarNext about its services and agree not to do so. You also agree that you will not imply that you and CarNext are affiliated in any way or that CarNext approves of your comments. We reserve the right to revoke our permission for Social Distribution at any time and for any reason and you agree to immediately cease Social Distribution upon notice of revocation and to comply with any terms we post in connection with the Social Distribution of Materials.</p>
                        <p>NOTICE TO THIRD PARTY SITES: Any Materials made available in connection with your web page, social networking site, or otherwise, third party widgets or otherwise is our exclusive property and no grant of any intellectual property rights is made by us. We retain the right to demand that you cease any use of our Materials upon notice.</p>

                        <p id="section12"><strong>12. MOBILE FEATURES</strong></p>
                        <p>The Platform may offer features that are available to you via your mobile phone or other mobile device. These features may include the ability to upload content to the Platform, access content and features, receive messages, download applications to your mobile phone or access CarNext features (collectively, “Mobile Features”). Message and data rates and other carrier fees may apply. Fees and charges that go through your carrier will appear on your mobile device bill or be deducted from your pre-paid balance. Your carrier may prohibit or restrict certain Mobile Features and certain Mobile Features may be incompatible with your carrier or mobile device. Please contact your carrier with questions regarding these issues. As applicable, instructions regarding how to opt-out of Mobile Features will be disclosed in connection with Mobile Features. For example, the instructions may require you to text a keyword (e.g. “STOP”) to the applicable short code for the Mobile Feature.</p>
                        <p>You agree that the Mobile Features for which you are registered may send communications to your mobile device regarding CarNext. Further, we may collect information related to your use of the Mobile Features as described in our <a href="{{ route('privacy') }}">Privacy Policy</a>. If you have registered for Mobile Features that utilize your mobile number, you agree to notify CarNext of any changes to or deactivation of your mobile number and update your account(s) on the Platform to reflect this change.</p>

                        <p id="section13"><strong>13. LINKING POLICY</strong></p>
                        <p>CarNext grants you the revocable permission to link to the Platform; provided, however, that any link to the Platform: (a) must not frame or create a browser or border environment around any of the content on the Platform or otherwise mirror any part of the Platform; (b) must not imply that CarNext or the Platform are endorsing or sponsoring any third party or its products or services, unless CarNext has given the third party prior written consent; (c) must not present false information about, or disparage, tarnish, or otherwise, in CarNext’s sole opinion, harm CarNext or its products or services; (d) must not use any CarNext’s trademarks without the prior written permission from CarNext; (e) must not contain content that could be construed as distasteful, offensive or controversial or otherwise objectionable (in CarNext’s sole opinion); and (f) must be owned and controlled by you or the person or entity placing the link, or otherwise permit you to enable such link subject to these Platform Terms. By linking to the Platform, you agree that you do and will continue to comply with the above linking requirements. Notwithstanding anything to the contrary contained in these Platform Terms, CarNext reserves the right to prohibit linking to the Platform for any reason in our sole and absolute discretion.</p>

                        <p id="section14"><strong>14. CONTESTS, SWEEPSTAKES, AND OTHER INTERACTIVE TRANSACTIONS</strong></p>
                        <p>The Platform may offer you opportunities to vote on certain matters and to enter contests and sweepstakes or other promotions, which may be governed by a separate set of rules that describe the sweepstakes or promotion and may have eligibility requirements, such as age or geographic area restrictions. It is your responsibility to read those rules to determine whether or not your participation, registration, or entry will be valid and to determine the sponsor’s requirements of you in connection with the applicable contest, sweepstakes, or other promotion. By casting a vote or entering contests or sweepstakes, you signify your agreement to all the terms set forth on the Platform applicable to the balloting, contest, or sweepstakes, as well as to the terms set forth in these Platform Terms and in our <a href="{{ route('privacy') }}">Privacy Policy</a>. See our <a href="{{ route('privacy') }}">Privacy Policy</a> for further information.</p>

                        <p id="section15"><strong>15. DISCLAIMER OF WARRANTIES; WAIVER</strong></p>
                        <p>a. To the fullest extent permitted by applicable law, the Platform and the Materials contained therein are provided on an “as is,” “as available” and “with all faults” basis without warranties of any kind, express or implied. You expressly agree that your use of the Platform, including all content or data distributed by or downloaded or accessed from or through the Platform, and your participation in the Platform (including providing listings and making bids and instant offers), is at your sole risk. CarNext, and its parent companies, affiliated entities, vendors, service providers, licensors, and suppliers, and the directors, officers, employees, affiliates, agents, contractors, interns, and other representatives of each of them (collectively, “CarNext Parties”) disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, durability, title, custom, trade, quiet enjoyment, non-infringement, system integration, and freedom from computer virus, as to the Platform and any Materials. CarNext does not represent or warrant that the Platform (or Materials) will meet your requirements or that the Platform (and Materials) are accurate, complete, uninterrupted, current, reliable, or error-free; or that defects will be corrected. You agree that we may disable it for indefinite periods of time or shut down the Platform (or any feature thereof) at any time, without notice to you. The CarNext Parties will have no liability for any such issues.</p>
                        <p>b. CarNext is not responsible for typographical errors or omissions on the Platform. We cannot and do not represent or warrant that the Platform or its server(s) are free of viruses or other harmful components, including content that is posted by third parties.</p>
                        <p>c. If you are dissatisfied with the Platform, your sole and exclusive remedy is to discontinue using it. By accessing or using the Platform you represent and warrant that your activities are lawful in every jurisdiction where you access or use the Platform. The CarNext Parties do not warrant that your use of the Platform is lawful in any particular jurisdiction and the CarNext Parties specifically disclaim such warranties.</p>

                        <p id="section16"><strong>16. LIMITATION OF LIABILITY</strong></p>
                        <p>a. To the maximum extent permitted by applicable law, in no event will any CarNext Party be liable to you or anyone else for any injury, loss, claim, or direct, indirect, special, incidental, consequential or punitive damages of any kind (including but not limited to loss of use, loss of profits, lost revenue, lost savings, replacement costs or loss of data or similar damages) whether in an action in contract, tort (including, but not limited to, negligence), strict liability, equity or otherwise, arising out of or in any way connected with: (i) the Platform or Materials; (ii) User Content; (iii) the use of, or the inability to use, the Platform or Materials; (iv) action taken in connection with an investigation by the CarNext Parties or law enforcement authorities regarding your use of the Platform; (v) action taken in connection with copyright or other intellectual property owners; (vi) any errors or omissions in the Platform’s technical operation; (vii) any damage that results from events beyond our reasonable control, such as damages to any user’s computer, mobile device, or other equipment or technology including, without limitation, damage from any security breach or from any virus, bugs, tampering, fraud, error, omission, interruption, defect, delay in operation or transmission, computer line or network failure or any other technical or other malfunction – even if foreseeable or even if the CarNext Parties have been advised of or should have known of the possibility of such damages. In no event will the total liability to you by the CarNext Parties for any claims, damages, losses, and causes of action exceed the amount you paid us, if any, for accessing the Platform or, if you did not pay us, the amount of ten United States dollars ($10.00). This limitation on damages is not intended to limit any obligation to pay prevailing party costs or fees as required by law or to limit or exclude liability for personal injury or property damage caused by the CarNext Parties, or for the gross negligence, fraud, or intentional, willful, malicious, or reckless misconduct by the CarNext Parties – but only to the extent that such liability cannot be limited or excluded pursuant to applicable law. This limitation on damages is also not intended to restrict any California resident’s right under applicable law (if any) to seek public injunctive relief, as otherwise in accordance with the dispute-resolution procedures set out below.</p>
                        <p>b. By accessing and using the Platform, you hereby release the CarNext Parties from any and all claims, damages or losses of any kind or nature whatsoever, whether known or unknown, suspected, or unsuspected, that you may have against them arising out of or in any way relating to the Platform.</p>
                        <p>By accessing the Platform, you understand that you may be waiving rights with respect to claims that are at this time unknown or unsuspected, and in accordance with such waiver, you acknowledge that you have read and understand, and expressly waive, the benefits of Section 1542 of the Civil Code of California, and any similar law of any state or territory which provides as follows:</p>
                        <p>“A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party.”</p>

                        <p id="section17"><strong>17. INDEMNITY</strong></p>
                        <p>To the fullest extent permitted by applicable law, you agree to defend, indemnify, and hold harmless the CarNext Parties from and against any and all claims, demands, damages, losses, costs, investigations, liabilities, judgments, settlements, and expenses, including (but not limited to) reasonable attorney’s fees, made by any third party, due to, arising out of, or directly or indirectly related to: (i) your breach (or anticipatory breach) of any of these Platform Terms; (ii) your content and materials, including (but not limited to) User Content; (iii) your use of the Platform, Materials, other than as permitted by us; (iv) your violation of laws, rules, regulations, codes, statutes, ordinances, or orders of any governmental or quasi-governmental authorities, including, without limitation, all administrative and legislative authorities or any agreement you have with a third party; (v) information or material transmitted through your computer, even if not submitted by you, that infringes, violates or misappropriates any copyright, trademark, trade secret, trade dress, patent, publicity, privacy or other rights of any person or similar matter; (vi) any misrepresentation made by you; or (vii) the CarNext Parties’ use of your content or information as permitted under these Platform Terms, the <a href="{{ route('privacy') }}">Privacy Policy</a>, or any other written agreement between you and CarNext. The CarNext Parties reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such cases, you agree to cooperate with us to defend such claim. You will not in any event settle any claim without the prior written consent of a duly authorized employee of CarNext.</p>

                        <p id="section18"><strong>18. APPLICABLE LAW AND VENUE</strong></p>
                        <p>DE Except as otherwise provided in the <a href="#">Binding Arbitration Agreement</a>, these Platform Terms, your use of the Platform and Materials, and any transactions thereunder shall be governed by and construed in accordance with the laws of the State of Delaware applicable to agreements made and entirely to be performed within the State of Illinois, without resort to its conflict of law provisions. You agree that any disputes arising out of or relating to these Platform Terms or your use of the Platform not subject to the Binding Arbitration will be heard only in state or federal court located in Kent County, Delaware, and you hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction of such courts.</p>

                        <p id="section19"><strong>19. BINDING ARBITRATION AGREEMENT</strong></p>
                        <p>As part of these Platform Terms, you and CarNext each agree as follows (the “Arbitration Agreement”).</p>
                        <p>a. Applicability of Arbitration Agreement. You agree that any dispute or controversy or claim arising out of or relating to the Platform, use of the Platform (and Materials), and/or these Platform Terms or any Additional Terms (including, without limitation, the arbitrability of any claim or controversy), or to any aspect of your relationship with CarNext will be resolved by binding arbitration, rather than in court, except that (1) you may assert claims in small claims court if your claims qualify, so long as the matter remains in such court and advances only on an individual (non-class, non-representative) basis; and (2) you or CarNext may seek equitable relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents). You agree that you must commence any arbitration or other claim within one (1) year after the dispute arises, otherwise the claim is permanently barred, which means that you will no longer have the right to assert a claim regarding the dispute. This Arbitration Agreement will apply, without limitation, to all claims that arose or were asserted before the effective date of these Platform Terms or any prior version of this Arbitration Agreement.</p>
                        <p>If you agree to arbitration with CarNext, you are agreeing in advance that you will not participate in or seek to recover monetary or other relief in any lawsuit filed against the CarNext Parties alleging class, collective, and/or representative claims on your behalf. Instead, by agreeing to arbitration, you may bring your claims against the CarNext Parties in an individual arbitration proceeding (except for any Batch Arbitration, as described below). If successful in such claims, you could be awarded money or other relief by an arbitrator. You acknowledge that you have been advised that you may consult with an attorney in deciding whether to accept this agreement, including this Arbitration Agreement.</p>
                        <p>The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement.</p>
                        <p>b. Process. To begin a claim, you must first send a letter describing your claim in detail, including your name and contact information, your legal claim, the specific facts giving rise to your claim (including the date(s) and amount(s) of any relevant transaction or interaction with us), and the requested relief) to 722 Dulaney Valley Rd, Suite #332</p>
                        <p>c. You and we agree to attempt in good faith to negotiate an informal resolution of your claim. If a resolution is not reached within thirty (30) days, you may commence arbitration action as set forth herein. The arbitration will be conducted by JAMS, an established alternative dispute resolution provider. Disputes involving claims and counterclaims under $250,000, not inclusive of attorneys' fees and interest, will be subject to JAMS's most current version of the Streamlined Arbitration Rules and procedures available at <a href="http://www.jamsadr.com/rules-streamlined-arbitration/">http://www.jamsadr.com/rules-streamlined-arbitration/</a>; all other claims will be subject to JAMS's most current version of the Comprehensive Arbitration Rules and Procedures, available at <a href="http://www.jamsadr.com/rules-comprehensive-arbitration/">http://www.jamsadr.com/rules-comprehensive-arbitration/</a>. JAMS's rules are also available at <a href="http://www.jamsadr.com">www.jamsadr.com</a> or by calling JAMS at 800-352-5267. If JAMS is not available to arbitrate, the parties will select an alternative arbitral forum. You may choose to have the arbitration conducted by telephone, based on written submissions, or in person in the county where you live or at another mutually agreed location. CarNext will be entitled to make an offer of judgment in the arbitration proceeding. If the offer of judgment is not accepted, and the award is not more favorable than the unaccepted offer, you will be solely responsible for all costs incurred by CarNext after the offer of judgment is made to the extent permitted by applicable law. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.</p>
                        <p>d. Fees. If the arbitrator finds that you cannot afford to pay JAMS's filing, administrative, hearing and/or other fees, and you cannot obtain a waiver from JAMS, CarNext will pay them for you. If the arbitrator determines the claims are frivolous, you agree to pay CarNext’s attorneys’ fees and costs in the arbitration, to the extent permitted by applicable law.</p>
                        <p>e. Authority of Arbitrator. The arbitrator, and not any federal, state, or local court or agency will have exclusive authority to resolve any dispute related to the interpretation, applicability, enforceability, or formation of this Arbitration Agreement including, but not limited to, any claim that all or any part of this Arbitration Agreement is void or voidable. The arbitration will decide the rights and liabilities, if any, of you and CarNext. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator will have the authority to grant motions dispositive of all or part of any claim. The arbitrator will have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the arbitral forum's rules, and these Platform Terms (including the Arbitration Agreement). The arbitrator will issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.</p>
                        <p>f. Waiver of Jury Trial. You and CarNext hereby waive any constitutional and statutory rights to sue in court and have a trial in front of a judge or a jury. You and CarNext are instead electing that all claims and disputes will be resolved by arbitration under this Arbitration Agreement, except as specified in paragraph (a) above. An arbitrator can award on an individual basis the same damages and relief as a court and must follow this Agreement as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.</p>
                        <p>g. Waiver of Class or Consolidated Actions. Except with respect to Batch Arbitration (as defined below), all claims and disputes within the scope of this Arbitration Agreement must be arbitrated on an individual basis and not on a class basis, only individual relief is available, and claims of more than one customer or user cannot be arbitrated or consolidated with those of any other customer or user. In the event that this subparagraph is deemed invalid or unenforceable neither you nor we are entitled to arbitration and instead claims, and disputes will be resolved in court.</p>
                        <p>You and CarNext agree that, in the event that there are fifty (50) or more individual requests for arbitration of a similar nature filed against CarNext within an approximately thirty-day period (or otherwise in close proximity), regardless of the state(s) in which such claims are filed, JAMS will administer all such similarly situated arbitration demands on a collective basis as a single, consolidated arbitration (subject to a single set of fees, proceeding schedule, and, if required, hearing) before a single arbitrator in accordance with the requirements outlined elsewhere in this section, provided that – in the event that the arbitrator deems it impracticable or inequitable to administer all such claims collectively in a single arbitration – (s)he may group demands for arbitration into groups of not fewer than twenty (20) matters, plus a remainder group as needed (or as otherwise deemed by the arbitrator to be practicable, equitable, and in best keeping with the spirit of this provision) and arbitrate each group of matters as a single, consolidated arbitration (structure a “Batch Arbitration”). You and CarNext agree (1) to work with JAMS in good faith to facilitate the resolution of disputes on a Batch Arbitration basis and (2) that requests for arbitration are of a “similar nature” if they arise out of the same event, agreement, or factual scenario and raise the same or similar legal issues and seek the same or similar relief. Disagreements over the applicability of this Batch Arbitration process will be settled in a single, consolidated arbitration proceeding that includes all affected parties and is resolved by a single arbitrator subject to the requirements of this section. This Batch Arbitration provision shall in no way be interpreted as authorizing a class or collective arbitration or action of any kind, or any suit or arbitration involving joint or consolidated claims, under any circumstances other than those expressly set forth in this section.</p>
                        <p>h. 30-Day Right to opt Out. You have the right to opt out of the provisions of this Arbitration Agreement by sending written notice of your decision to opt out by contacting us at <a href="mailto:support@carnext.autos">support@carnext.autos</a>, within 30 days after first becoming subject to this Arbitration Agreement. Your notice must include your name and address, the email address you used to set up your CarNext account (if you have one), and an unequivocal statement that you want to opt out of this Arbitration Agreement. If you opt out of this Arbitration Agreement, all other parts of these Platform Terms will continue to apply to you. Opting out of this Arbitration Agreement has no effect on any other arbitration agreements that you may currently have, or may enter in the future, with us.</p>
                        <p>i. Severability. If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts will be of no force and effect and will be severed and the remainder of the Arbitration Agreement will continue in full force and effect.</p>
                        <p>j. Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with CarNext.</p>
                        <p>k. Modification. Notwithstanding any provision in these Platform Terms to the contrary, we agree that if CarNext makes any future material change to this Arbitration Agreement, it will not apply to any individual claim(s) that you had already provided notice to CarNext.</p>

                        <p id="section20"><strong>20. LOCATION OF THE PLATFORM AND TERRITORIAL RESTRICTIONS</strong></p>
                        <p>a. CarNext controls and operates the Platform from offices located in the United States of America. The information and content provided through the Platform are not intended for distribution to, or use by, any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject CarNext to any registration requirement within such jurisdiction or country. We reserve the right to limit the availability of the Platform or any portion of the Platform, to any person, geographic area, or jurisdiction, at any time and in our sole discretion. If you use the Platform from other locations, you are responsible for compliance with applicable local laws.</p>
                        <p>b. Software related to or made available by the Platform may be subject to United States export controls. Thus, no software from the Platform may be downloaded, exported or re-exported: (a) into (or to a national or resident of) Cuba, North Korea, Iran, Syria or any other country or region to which the United States has embargoed goods or that has been designated by the U.S. government as “terrorist supporting”; or (b) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Commerce Department's Table of Deny Orders, or (c) to any country or individual in a manner prohibited under the export control laws of the United States or Canada. By downloading any software related to this Platform, you represent and warrant that you are not located in, under the control of, or a national or resident of, any such country or on any such list.</p>

                        <p id="section21"><strong>21. GENERAL-AUDIENCE SITE</strong></p>
                        <p>The Platform and its services are not directed to, and not intended for the use of, children younger than 18 years old. If you are a minor, you should not contact or otherwise provide personal information to our Platform.</p>

                        <p id="section22"><strong>22. SPECIAL TERMS FOR APPLE IOS USERS</strong></p>
                        <p>Notwithstanding any other provision within these Platform Terms, the following additional terms are applicable to those using any CarNext application on an Apple iOS device: You understand that these Platform Terms are between you and CarNext only and not Apple, Inc. (“Apple”) and that CarNext (or the third party develop that may own and operate the Mobile Features) are responsible for the Mobile Features and the content thereof, but that Apple and its subsidiaries are third-party beneficiaries of these Platform Terms and have the right to enforce them against you. You understand that, should the Mobile Features fail to conform to any applicable warranty not disclaimed above, you may notify Apple and Apple will refund the purchase price (if any), but that Apple has no maintenance, support, or (to the maximum extent permitted by applicable law) other warranty obligations to you with regard to the Mobile Features. Apple is not responsible for any product liability claims or claims that the Mobile Features or your use thereof fails to conform to any applicable legal or regulatory requirement or infringes a third party’s intellectual property rights. If you have any questions or concerns regarding the Mobile Features, please contact CarNext as described below.</p>

                        <p id="section23"><strong>23. CHANGES TO THESE TERMS</strong></p>
                        <p>To the maximum extent allowed by applicable law, CarNext reserves the right to change or modify any of the terms and conditions contained in these Platform Terms, or any policy of the Platform, from time to time at any time and in its sole discretion (“Updated Terms”). If CarNext decides to change these Platform Terms or a Platform policy, it will post the Updated Terms on the Platform and update the effective date set forth above. We may – in our discretion – also notify you of material changes via email if you have provided us with your email address. Any changes or modifications to these Platform Terms will be effective upon posting of the Updated Terms (or at such later date as we may specify in the Updated Terms). Your continued use of the Platform following posting of any changes or modifications (or some other act that we reasonably specify) constitutes your acceptance of the Updated Terms. You should frequently review these Platform Terms and any other applicable policies, including their dates, to understand the terms and conditions that apply to your use of the Platform.</p>

                        <p id="section24"><strong>24. GENERAL TERMS</strong></p>
                        <p>If CarNext does not act after you or others breach these Platform Terms, it does not waive CarNext’s right to act in the future with respect to such breach or any subsequent breaches. No waiver by CarNext of any of these Platform Terms will be of any force or effect unless made in writing and signed by a duly authorized officer of CarNext. Neither the course of conduct between the parties nor trade practice will act to modify these Platform Terms.</p>
                        <p>CarNext may assign its rights and duties under these Platform Terms to any party at any time without any notice to you. Platform Terms may not be assigned by you without CarNext’s prior written consent. You represent to us that you have the authority to register with the Platform according to these Platform Terms.</p>
                        <p>You agree that these Platform Terms will not be construed against CarNext because CarNext has drafted them.</p>
                        <p>If any provision of these Platform Terms is held unlawful, void, or for any reason unenforceable for any reason, then that provision will be deemed severable from these Platform Terms and will not affect the validity and enforceability of any remaining provisions.</p>
                        <p>If a court or other decision-maker should determine that any provisions of these Platform Terms is overbroad, unfair, or unreasonable, such provision shall be given effect to the maximum extent possible by narrowing or enforcing in part that aspect of the provision found overbroad or unreasonable. The Section titles are inserted only as a matter of convenience and have no legal or contractual effect.</p>
                        <p>No amendment to or modification of these Platform Terms, or action, or delay, will be binding unless in writing and signed by CarNext. Provisions of these Platform Terms that would logically survive termination will survive the termination of these Platform Terms, including (but not limited to) Disclaimer of Warranties; Waiver, Limitation of Liability, Arbitration and Indemnity.</p>
                        <p>The communications between you and us use electronic means, whether you visit the Platform or send us emails or other electronic communications, or whether we post notices on the Platform or communicate with you via email or other electronic communications. You (1) consent to receive communications from us in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that CarNext provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing. The foregoing does not affect your statutory rights.</p>
                        <p>These Platform Terms and any Additional Terms constitute the entire understanding between the parties as to subject matter hereof and supersede all prior agreements and understandings.</p>

                        <p id="section25"><strong>25. CONTACT INFORMATION</strong></p>
                        <p>If you have any questions about our Platform Terms, please contact us at <a href="tel:9044796224">9044796224</a></p>

                </div>
            </div>
        </div>
    </div>
    
</section>


@endsection

