<?php
return [
    // Application Constants
   
    'COLOR' => [
        "Black" => "#000000",
        "Gray" => "#808080",
        "Charcoal" => "#36454F",
        "Ebony" => "#555D50",
        "Jet Black" => "#0A0A0A",
        "Tan" => "#D2B48C",
        "Beige" => "#F5F5DC",
        "Medium Dark Slate" => "#2F4F4F",
        "Graphite" => "#53565A",
        "Titan Black" => "#3F3F3F",
        "Brown" => "#A52A2A",
        "Sandstone" => "#C9B092",
        "Red" => "#FF0000",
        "Grey" => "#BEBEBE",
        "Light Gray" => "#D3D3D3",
        "White" => "#FFFFFF",
        "Ivory" => "#FFFFF0",
        "Medium Gray" => "#B2BEB5",
        "Cognac" => "#7C4C3A",
        "Dark Gray" => "#A9A9A9",
        "Carbon Black" => "Blank",
        "Light Slate" => "#B2BEB5",
        "Black/Black" => "#080808",
        "Cement" => "#D5D5D5",
        "Okapi Brown" => "#7B5C38",
        "Bk" => "#000000",
        "Blue" => "#0000FF",
        "Silver" => "#C0C0C0",
        "Dark Slate Gray" => "#2F4F4F",
    ],

    'BODY_TYPE' => [
        'coupe' => 'coupe.png',
        'hatchback' => 'hatchback.png',
        'minivan' => 'minivan.png',
        'muv' => 'muv.png',
        'pickup' => 'pickup.png',
        'pickup-truck' => 'pickup-truck.png',
        'sedan' => 'sedan.png',
        'suv' => 'suv.png',
        'wagon' => 'wagon.png',
        'minivan' => 'minivan.png',
        
    ],
    
    'COUNTRY_CODE' => [
        ["code" => "1", "name" => "US"],
       // ["code" => "44", "name" => "United Kingdom"],
        ["code" => "91", "name" => "IN"],
        /*["code" => "61", "name" => "Australia"],
        ["code" => "81", "name" => "Japan"],
        ["code" => "86", "name" => "China"],
        ["code" => "49", "name" => "Germany"],
        ["code" => "33", "name" => "France"],
        ["code" => "39", "name" => "Italy"],
        ["code" => "55", "name" => "Brazil"],
        ["code" => "7", "name" => "Russia"],
        ["code" => "93", "name" => "Afghanistan"],
        ["code" => "355", "name" => "Albania"],
        ["code" => "213", "name" => "Algeria"],
        ["code" => "376", "name" => "Andorra"],
        ["code" => "244", "name" => "Angola"],
        ["code" => "54", "name" => "Argentina"],
        ["code" => "374", "name" => "Armenia"],
        ["code" => "297", "name" => "Aruba"],
        ["code" => "43", "name" => "Austria"],
        ["code" => "994", "name" => "Azerbaijan"],
        ["code" => "973", "name" => "Bahrain"],
        ["code" => "880", "name" => "Bangladesh"],
        ["code" => "375", "name" => "Belarus"],
        ["code" => "32", "name" => "Belgium"],
        ["code" => "501", "name" => "Belize"],
        ["code" => "229", "name" => "Benin"],
        ["code" => "975", "name" => "Bhutan"],
        ["code" => "591", "name" => "Bolivia"],
        ["code" => "387", "name" => "Bosnia and Herzegovina"],
        ["code" => "267", "name" => "Botswana"],
        ["code" => "673", "name" => "Brunei"],
        ["code" => "359", "name" => "Bulgaria"],
        ["code" => "226", "name" => "Burkina Faso"],
        ["code" => "257", "name" => "Burundi"],
        ["code" => "855", "name" => "Cambodia"],
        ["code" => "237", "name" => "Cameroon"],
        ["code" => "238", "name" => "Cape Verde"],
        ["code" => "236", "name" => "Central African Republic"],
        ["code" => "235", "name" => "Chad"],
        ["code" => "56", "name" => "Chile"],
        ["code" => "57", "name" => "Colombia"],
        ["code" => "269", "name" => "Comoros"],
        ["code" => "242", "name" => "Congo"],
        ["code" => "243", "name" => "Congo, Democratic Republic of the"],
        ["code" => "506", "name" => "Costa Rica"],
        ["code" => "225", "name" => "Côte d'Ivoire"],
        ["code" => "385", "name" => "Croatia"],
        ["code" => "53", "name" => "Cuba"],
        ["code" => "357", "name" => "Cyprus"],
        ["code" => "420", "name" => "Czech Republic"],
        ["code" => "45", "name" => "Denmark"],
        ["code" => "253", "name" => "Djibouti"],
        ["code" => "670", "name" => "East Timor"],
        ["code" => "593", "name" => "Ecuador"],
        ["code" => "20", "name" => "Egypt"],
        ["code" => "503", "name" => "El Salvador"],
        ["code" => "240", "name" => "Equatorial Guinea"],
        ["code" => "291", "name" => "Eritrea"],
        ["code" => "372", "name" => "Estonia"],
        ["code" => "251", "name" => "Ethiopia"],
        ["code" => "679", "name" => "Fiji"],
        ["code" => "358", "name" => "Finland"],
        ["code" => "241", "name" => "Gabon"],
        ["code" => "220", "name" => "Gambia"],
        ["code" => "995", "name" => "Georgia"],
        ["code" => "233", "name" => "Ghana"],
        ["code" => "350", "name" => "Gibraltar"],
        ["code" => "30", "name" => "Greece"],
        ["code" => "299", "name" => "Greenland"],
        ["code" => "502", "name" => "Guatemala"],
        ["code" => "224", "name" => "Guinea"],
        ["code" => "245", "name" => "Guinea-Bissau"],
        ["code" => "592", "name" => "Guyana"],
        ["code" => "509", "name" => "Haiti"],
        ["code" => "504", "name" => "Honduras"],
        ["code" => "36", "name" => "Hungary"],
        ["code" => "354", "name" => "Iceland"],
        ["code" => "62", "name" => "Indonesia"],
        ["code" => "98", "name" => "Iran"],
        ["code" => "964", "name" => "Iraq"],
        ["code" => "353", "name" => "Ireland"],
        ["code" => "972", "name" => "Israel"],
        ["code" => "962", "name" => "Jordan"],
        ["code" => "254", "name" => "Kenya"],
        ["code" => "686", "name" => "Kiribati"],
        ["code" => "965", "name" => "Kuwait"],
        ["code" => "996", "name" => "Kyrgyzstan"],
        ["code" => "856", "name" => "Laos"],
        ["code" => "371", "name" => "Latvia"],
        ["code" => "961", "name" => "Lebanon"],
        ["code" => "266", "name" => "Lesotho"],
        ["code" => "231", "name" => "Liberia"],
        ["code" => "218", "name" => "Libya"],
        ["code" => "423", "name" => "Liechtenstein"],
        ["code" => "370", "name" => "Lithuania"],
        ["code" => "352", "name" => "Luxembourg"],
        ["code" => "389", "name" => "North Macedonia"],
        ["code" => "261", "name" => "Madagascar"],
        ["code" => "265", "name" => "Malawi"],
        ["code" => "60", "name" => "Malaysia"],
        ["code" => "960", "name" => "Maldives"],
        ["code" => "223", "name" => "Mali"],
        ["code" => "356", "name" => "Malta"],
        ["code" => "692", "name" => "Marshall Islands"],
        ["code" => "222", "name" => "Mauritania"],
        ["code" => "230", "name" => "Mauritius"],
        ["code" => "52", "name" => "Mexico"],
        ["code" => "691", "name" => "Micronesia"],
        ["code" => "373", "name" => "Moldova"],
        ["code" => "377", "name" => "Monaco"],
        ["code" => "976", "name" => "Mongolia"],
        ["code" => "382", "name" => "Montenegro"],
        ["code" => "212", "name" => "Morocco"],
        ["code" => "258", "name" => "Mozambique"],
        ["code" => "95", "name" => "Myanmar"],
        ["code" => "264", "name" => "Namibia"],
        ["code" => "977", "name" => "Nepal"],
        ["code" => "31", "name" => "Netherlands"],
        ["code" => "64", "name" => "New Zealand"],
        ["code" => "505", "name" => "Nicaragua"],
        ["code" => "227", "name" => "Niger"],
        ["code" => "234", "name" => "Nigeria"],
        ["code" => "47", "name" => "Norway"],
        ["code" => "968", "name" => "Oman"],
        ["code" => "92", "name" => "Pakistan"],
        ["code" => "680", "name" => "Palau"],
        ["code" => "507", "name" => "Panama"],
        ["code" => "675", "name" => "Papua New Guinea"],
        ["code" => "595", "name" => "Paraguay"],
        ["code" => "51", "name" => "Peru"],
        ["code" => "63", "name" => "Philippines"],
        ["code" => "48", "name" => "Poland"],
        ["code" => "351", "name" => "Portugal"],
        ["code" => "974", "name" => "Qatar"],
        ["code" => "40", "name" => "Romania"],
        ["code" => "250", "name" => "Rwanda"],
        ["code" => "685", "name" => "Samoa"],
        ["code" => "378", "name" => "San Marino"],
        ["code" => "239", "name" => "São Tomé and Príncipe"],
        ["code" => "966", "name" => "Saudi Arabia"],
        ["code" => "221", "name" => "Senegal"],
        ["code" => "381", "name" => "Serbia"],
        ["code" => "248", "name" => "Seychelles"],
        ["code" => "232", "name" => "Sierra Leone"],
        ["code" => "65", "name" => "Singapore"],
        ["code" => "421", "name" => "Slovakia"],
        ["code" => "386", "name" => "Slovenia"],
        ["code" => "677", "name" => "Solomon Islands"],
        ["code" => "252", "name" => "Somalia"],
        ["code" => "27", "name" => "South Africa"],
        ["code" => "82", "name" => "South Korea"],
        ["code" => "211", "name" => "South Sudan"],
        ["code" => "34", "name" => "Spain"],
        ["code" => "94", "name" => "Sri Lanka"],
        ["code" => "249", "name" => "Sudan"],
        ["code" => "597", "name" => "Suriname"],
        ["code" => "268", "name" => "Swaziland"],
        ["code" => "46", "name" => "Sweden"],
        ["code" => "41", "name" => "Switzerland"],
        ["code" => "963", "name" => "Syria"],
        ["code" => "886", "name" => "Taiwan"],
        ["code" => "992", "name" => "Tajikistan"],
        ["code" => "255", "name" => "Tanzania"],
        ["code" => "66", "name" => "Thailand"],
        ["code" => "670", "name" => "Timor-Leste"],
        ["code" => "228", "name" => "Togo"],
        ["code" => "676", "name" => "Tonga"],
        ["code" => "216", "name" => "Tunisia"],
        ["code" => "90", "name" => "Turkey"],
        ["code" => "993", "name" => "Turkmenistan"],
        ["code" => "688", "name" => "Tuvalu"],
        ["code" => "256", "name" => "Uganda"],
        ["code" => "380", "name" => "Ukraine"],
        ["code" => "971", "name" => "United Arab Emirates"],
        ["code" => "598", "name" => "Uruguay"],
        ["code" => "998", "name" => "Uzbekistan"],
        ["code" => "678", "name" => "Vanuatu"],
        ["code" => "58", "name" => "Venezuela"],
        ["code" => "84", "name" => "Vietnam"],
        ["code" => "967", "name" => "Yemen"],
        ["code" => "260", "name" => "Zambia"],
        ["code" => "263", "name" => "Zimbabwe"],*/
    ],
    'LIFESTYLE' =>[
        'FAMILY'=>[
            //'trim'=>["Base", "SE", "S", "LX", "LE", "Limited", "SV", "EX", "Premium", "SEL", "EX-L", "LS", "XLE"],
            //'cylinders'=>["4", "6"],
            'fuel_type'=>["Unleaded"],
            'body_type'=>["Minivan"],
            'engine'=>[ "3.5L V6"],
            'transmission'=>[ "Automatic"],
            //'seating_capacity'=> ["5", "6", "7", "8"],
            'drivetrain'=>["FWD"] ,
            //'powertrain_type'=> ["Combustion", "HEV", "MHEV", "PHEV"],
            //'high_value_features'=>["automatic transmission", "brake assist", "keyless entry/locking", "bluetooth", "usb connection", "parking distance system", "steering wheel controls", "voice recognition", "backup camera", "blind spot system"],
        ],
        'SPORTS'=>[
            //'trim'=>["Sport", 'R' ,"S 560","C", "Performance Collection","Premium Performance","Premium Luxury","GT", "EcoBoost Premium", "GT Premium", "Si", "Performance", "ST", "GT-Line"],
            //'cylinders'=>["4", "6", "8", "10"],
            'fuel_type'=>["Premium Unleaded"],
            'body_type'=>["Coupe"],
            'engine'=>["4.0L V8", "5.2L V10", "3.6L V6", "3.8L H6"],
            'transmission'=>[ "Automatic"],
            //'seating_capacity'=> ["2", "4"],
            'drivetrain'=>["4WD","RWD", "AWD"] ,
            //'powertrain_type'=>["Combustion", "PHEV", "MHEV"] ,
            //'high_value_features'=>["automatic transmission","brake assist", "premium wheels", "voice recognition", "heated seats", "adaptive cruise control", "navigation", "premium audio",  "leather seats"],    
        ],
        
        'LUXURY'=>[
            //'trim'=>["Luxury", "Platinum", "Premium Luxury","Limited", "Premium Plus", "C300", "Titanium", "Premier", "Prestige", "Elite"],
            //'cylinders'=>["6", "8","12"],
            'fuel_type'=>["Unleaded"],
            'body_type'=>["Sedan"],
            'engine'=>["3.0L L6 DOHC 24V TURBO"],
            'transmission'=>[ "Automatic"],
            //'seating_capacity'=> ["4", "5", "6", "7"],
            'drivetrain'=>["AWD"] ,
            //'powertrain_type'=>["Combustion", "HEV", "MHEV", "PHEV", "BEV"] ,
            //'high_value_features'=>["automatic transmission", "premium wheels", "parking distance system", "voice recognition", "heated seats", "adaptive cruise control", "navigation", "premium audio", "leather seats", "memory seats", "power closing liftgate", "wireless charging/connection"],
        ],
        'COMPACT'=>[
            //'trim'=>["Base", "SE", "S", "LX", "LT", "LE", "Limited", "SV", "EX", "LS"],
            //'cylinders'=>["3", "4"],
            'fuel_type'=>["Unleaded"],
            'body_type'=>["Sedan"],
            'engine'=>[ "1.8L I4"],
            'transmission'=>[ "CVT"],
           
            //'seating_capacity'=>["5", "4"] ,
            'drivetrain'=>["FWD"] ,
            //'powertrain_type'=>["Combustion", "HEV", "MHEV", "BEV"],
            //'high_value_features'=>["automatic transmission", "brake assist", "keyless entry/locking", "bluetooth", "usb connection", "steering wheel controls", "voice recognition", "backup camera", "blind spot system"],
        ],
        'ADVENTURE'=>[
            //'trim'=>["Trailhawk", "Off-Road", "Adventure", "All-Terrain", "Rubicon", "TRD Off Road", "TRD Pro", "Trail"],
            //'cylinders'=>["4", "6", "8"],
            'fuel_type'=>["Unleaded"],
            'body_type'=>["SUV"],
            'engine'=>["3.6L V6"],
            'transmission'=>[ "Automatic"],
            //'seating_capacity'=> ["5", "7", "8"],
            'drivetrain'=> ["4WD"],
            //'powertrain_type'=> ["Combustion", "HEV", "PHEV"],
            //'high_value_features'=>["automatic transmission", "brake assist", "parking distance system", "voice recognition", "heated seats", "adaptive cruise control", "navigation", "fog lights", "trailer assist"]
        ],
    
    ]



];